# Site settings
title: ADL Scan
app_name: ADL Scan
email: adlscan3@gmail.com
url: https://adlscan.github.io
description: "Mobile utilities for you"

appstore_link                             : https://www.apple.com                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://www.google.com                                          # Enter Google Play Store URL.


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#412A18'
  links: '#219ab3'

# Footer settings
footer: ADL Scan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
